const header = document.getElementById("header");
const navbar = document.getElementById("navbar-links");

window.addEventListener("scroll", function () {
  if (this.window.scrollY > 50) {
    // up to 50px after change style
    header.classList.add("scrolled");
    navbar.classList.add("scrolled");
    header.classList.remove("transparent");
    navbar.classList.remove("transparent");
  } else {
    header.classList.add("transparent");
    navbar.classList.add("transparent");
    header.classList.remove("scrolled");
    navbar.classList.remove("scrolled");
  }
});

header.classList.add("transparent");
navbar.classList.add("transparent");
// heading style

function headers() {
  const navbar = document.getElementById("navbar-links");
  const more_btns = document.getElementById("menu-btns");
  const icon = more_btns.querySelector("i");

  // Toggle menu & icon
  more_btns.addEventListener("click", (e) => {
    e.stopPropagation(); // prevent immediate close
    navbar.classList.toggle("active");

    // icon toggle
    if (navbar.classList.contains("active")) {
      icon.classList.add("fa-xmark");
      icon.classList.remove("fa-bars-staggered");
    } else {
      icon.classList.add("fa-bars-staggered");
      icon.classList.remove("fa-xmark");
    }
  });
}
headers();

// First Version Data Store
const services = [
  // Department Link
  {
    main: "Ministries & Departments 🏛️",
    title: "President’s Office",
    url: "president.gov.lk/government",
    keywords: [
      "President office Sri Lanka",
      "presidential secretariat",
      "govt office",
      "president contact",
      "govt services",
      "Sri Lanka president",
      "official portal",
      "government administration",
      "presidential announcements",
      "public services",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Prime Minister’s Office",
    url: "pmoffice.gov.lk",
    keywords: [
      "Prime minister office",
      "PM secretariat",
      "govt Sri Lanka",
      "prime minister contact",
      "official portal",
      "Sri Lanka PM",
      "government updates",
      "PM announcements",
      "govt departments",
      "PM services",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Ministry of Finance",
    url: "gov.lk/webdirectory/ministry",
    keywords: [
      "finance ministry Sri Lanka",
      "budget info",
      "govt finance",
      "tax office",
      "financial regulations",
      "treasury Sri Lanka",
      "govt economic policy",
      "ministry contact",
      "govt portal",
      "finance services",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Ministry of Health",
    url: "gov.lk/webdirectory/ministry",
    keywords: [
      "health ministry",
      "hospitals",
      "clinics",
      "vaccinations Sri Lanka",
      "health services",
      "ministry contact",
      "govt health updates",
      "official health portal",
      "public health info",
      "Sri Lanka health department",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Ministry of Education",
    url: "gov.lk/webdirectory/ministry",
    keywords: [
      "education ministry",
      "schools",
      "universities",
      "scholarships",
      "govt education",
      "ministry contact",
      "official education portal",
      "academic info Sri Lanka",
      "research institutes",
      "education services",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Ministry of Agriculture",
    url: "gov.lk/webdirectory/ministry",
    keywords: [
      "agriculture ministry",
      "farming info",
      "crop management",
      "extension services",
      "govt agriculture",
      "ministry contact",
      "farmer services",
      "agri policies",
      "Sri Lanka agriculture",
      "official portal",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Ministry of Transport",
    url: "gov.lk/webdirectory/ministry",
    keywords: [
      "transport ministry",
      "traffic info",
      "driving license",
      "vehicle registration",
      "public transport Sri Lanka",
      "ministry contact",
      "official transport portal",
      "traffic fines",
      "road regulations",
      "vehicle services",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Ministry of Tourism",
    url: "gov.lk/webdirectory/ministry",
    keywords: [
      "tourism ministry",
      "national parks",
      "heritage sites",
      "cultural centers",
      "tourist info Sri Lanka",
      "ministry contact",
      "official tourism portal",
      "travel info",
      "tourism services",
      "sightseeing Sri Lanka",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Ministry of Justice",
    url: "gov.lk/webdirectory/ministry",
    keywords: [
      "justice ministry",
      "courts Sri Lanka",
      "legal aid",
      "police info",
      "ministry contact",
      "official justice portal",
      "law services",
      "legal assistance",
      "judiciary updates",
      "public legal info",
    ],
  },
  {
    main: "Ministries & Departments 🏛️",
    title: "Ministry of Environment",
    url: "gov.lk/webdirectory/ministry",
    keywords: [
      "environment ministry",
      "national parks",
      "forestry",
      "pollution control",
      "govt environmental policies",
      "ministry contact",
      "official environment portal",
      "conservation",
      "eco services",
      "Sri Lanka environment",
    ],
  },

  // Regional
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "Western Province Secretariat",
    url: "https://www.wpc.gov.lk/",
    keywords: [
      "Western province secretariat",
      "Colombo district office",
      "govt services Western",
      "provincial administration",
      "govt offices",
      "public services",
      "district contact",
      "Western Sri Lanka",
      "provincial updates",
      "official portal",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "Central Province Secretariat",
    url: "http://www.cp.gov.lk/",
    keywords: [
      "Central province secretariat",
      "Kandy district office",
      "govt services Central",
      "provincial admin",
      "public services",
      "district govt",
      "official portal",
      "Central Sri Lanka",
      "provincial contact",
      "govt info",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "Southern Province Secretariat",
    url: "http://www.sp.gov.lk/",
    keywords: [
      "Southern province secretariat",
      "Galle district office",
      "govt services Southern",
      "provincial admin",
      "public services",
      "district contact",
      "Sri Lanka Southern",
      "official portal",
      "govt updates",
      "provincial info",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "Northern Province Secretariat",
    url: "http://www.np.gov.lk/",
    keywords: [
      "Northern province secretariat",
      "Jaffna district office",
      "govt services Northern",
      "provincial admin",
      "public services",
      "district contact",
      "Sri Lanka Northern",
      "official portal",
      "govt updates",
      "provincial info",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "Eastern Province Secretariat",
    url: "http://www.ep.gov.lk/",
    keywords: [
      "Eastern province secretariat",
      "Trincomalee district office",
      "govt services Eastern",
      "provincial admin",
      "public services",
      "district contact",
      "Sri Lanka Eastern",
      "official portal",
      "govt updates",
      "provincial info",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "North Western Province Secretariat",
    url: "http://www.nwp.gov.lk/",
    keywords: [
      "North Western province secretariat",
      "Kurunegala district office",
      "govt services NWP",
      "provincial admin",
      "public services",
      "district contact",
      "Sri Lanka NWP",
      "official portal",
      "govt info",
      "provincial updates",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "North Central Province Secretariat",
    url: "http://www.ncp.gov.lk/",
    keywords: [
      "North Central province secretariat",
      "Anuradhapura district office",
      "govt services NCP",
      "provincial admin",
      "public services",
      "district contact",
      "Sri Lanka NCP",
      "official portal",
      "govt info",
      "provincial updates",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "Uva Province Secretariat",
    url: "http://www.up.gov.lk/",
    keywords: [
      "Uva province secretariat",
      "Badulla district office",
      "govt services Uva",
      "provincial admin",
      "public services",
      "district contact",
      "Sri Lanka Uva",
      "official portal",
      "govt info",
      "provincial updates",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺️",
    title: "Sabaragamuwa Province Secretariat",
    url: "http://www.sgp.gov.lk",
    keywords: [
      "Sabaragamuwa province secretariat",
      "Ratnapura district office",
      "govt services Sabaragamuwa",
      "provincial admin",
      "public services",
      "district contact",
      "Sri Lanka Sabaragamuwa",
      "official portal",
      "govt info",
      "provincial updates",
    ],
  },

  // Publics Services
  {
    main: "Public Services & Utilities ⚡🚰📮",
    title: "Ceylon Electricity Board (CEB)",
    url: "https://www.ceb.lk/",
    keywords: [
      "electricity bill Sri Lanka",
      "CEB online payment",
      "power outage info",
      "CEB contact",
      "electricity service",
      "CEB portal",
      "Sri Lanka electricity",
      "energy updates",
      "power services",
      "billing info",
    ],
  },
  {
    main: "Public Services & Utilities ⚡🚰📮",
    title: "Lanka Electricity Company (LECO)",
    url: "https://www.leco.lk/",
    keywords: [
      "LECO electricity",
      "billing info",
      "online payment",
      "power services",
      "LECO outage",
      "contact LECO",
      "energy Sri Lanka",
      "electricity portal",
      "LECO services",
      "utility info",
    ],
  },
  {
    main: "Public Services & Utilities ⚡🚰📮",
    title: "National Water Supply & Drainage Board (NWSDB)",
    url: "https://www.waterboard.lk/",
    keywords: [
      "water bill Sri Lanka",
      "NWSDB services",
      "water supply info",
      "online payment water",
      "govt water services",
      "contact water board",
      "drinking water info",
      "water management",
      "Sri Lanka water",
      "water utility portal",
    ],
  },
  {
    main: "Public Services & Utilities ⚡🚰📮",
    title: "Sri Lanka Post",
    url: "https://www.slpost.gov.lk/",
    keywords: [
      "Sri Lanka post",
      "postal service",
      "tracking parcel Sri Lanka",
      "post office contact",
      "mail services",
      "SL post portal",
      "postal info",
      "courier services",
      "stamp info",
      "official post website",
    ],
  },
  {
    main: "Public Services & Utilities ⚡🚰📮",
    title: "Telecom Regulatory Commission (TRC)",
    url: "https://www.trc.gov.lk/",
    keywords: [
      "telecom Sri Lanka",
      "mobile services",
      "internet regulation",
      "TRC portal",
      "mobile licenses",
      "broadband info",
      "govt telecom",
      "telecom updates",
      "Sri Lanka TRC",
      "regulatory info",
    ],
  },
  {
    main: "Public Services & Utilities ⚡🚰📮",
    title: "Sri Lanka Transport Board (SLTB)",
    url: "https://www.sltb.lk/",
    keywords: [
      "public transport",
      "bus schedules Sri Lanka",
      "SLTB info",
      "bus ticketing",
      "travel info",
      "bus routes",
      "SLTB portal",
      "govt transport services",
      "Sri Lanka buses",
      "official transport website",
    ],
  },
  {
    main: "Public Services & Utilities ⚡🚰📮",
    title: "Civil Aviation Authority (CAA)",
    url: "https://www.caa.lk",
    keywords: [
      "aviation Sri Lanka",
      "airport info",
      "flight schedules",
      "CAA regulations",
      "airline licensing",
      "airport services",
      "Sri Lanka aviation",
      "official CAA portal",
      "travel info",
      "air transport services",
    ],
  },
  {
    main: "Public Services & Utilities ⚡🚰📮",
    title: "Sri Lanka Railways",
    url: "https://www.railway.gov.lk/",
    keywords: [
      "train schedules Sri Lanka",
      "railway tickets",
      "Sri Lanka train info",
      "rail services",
      "official railway portal",
      "train booking online",
      "railway updates",
      "transport Sri Lanka",
      "railway contact",
      "passenger services",
    ],
  },

  // laws
  {
    main: "Law & Justice ⚖️👮",
    title: "Supreme Court of Sri Lanka",
    url: "http://www.supremecourt.lk/",
    keywords: [
      "Supreme Court Sri Lanka",
      "highest court",
      "court rulings",
      "legal decisions",
      "Sri Lanka judiciary",
      "SC portal",
      "official court website",
      "judge info",
      "case info",
      "court announcements",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Court of Appeal of Sri Lanka",
    url: "http://www.courtofappeal.lk/",
    keywords: [
      "Court of Appeal Sri Lanka",
      "appeal cases",
      "legal info",
      "judiciary portal",
      "court rulings",
      "judge info",
      "official website",
      "legal updates",
      "appeal process",
      "Sri Lanka courts",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "District Courts",
    url: "https://www.judiciary.lk/district-courts",
    keywords: [
      "district courts Sri Lanka",
      "local court info",
      "court schedules",
      "judge contacts",
      "official court portal",
      "judiciary Sri Lanka",
      "case status",
      "legal proceedings",
      "district legal info",
      "Sri Lanka judiciary",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Magistrate Courts",
    url: "https://www.judiciary.lk/magistrate-courts",
    keywords: [
      "magistrate courts",
      "local judiciary",
      "court info",
      "legal aid",
      "case info Sri Lanka",
      "official court portal",
      "magistrate contact",
      "judiciary services",
      "court schedules",
      "Sri Lanka legal system",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Police Department",
    url: "https://www.police.lk/",
    keywords: [
      "Sri Lanka police",
      "nearest police station",
      "police contact",
      "emergency number",
      "crime reporting",
      "police services",
      "law enforcement",
      "official police portal",
      "public safety",
      "police divisions",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Legal Aid Commission",
    url: "http://www.legalaid.gov.lk/",
    keywords: [
      "legal aid Sri Lanka",
      "free legal help",
      "lawyers Sri Lanka",
      "public legal assistance",
      "legal advice",
      "official portal",
      "legal services",
      "pro bono lawyers",
      "judiciary support",
      "legal guidance",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Attorney General’s Department",
    url: "http://www.attorneygeneral.gov.lk/",
    keywords: [
      "Attorney General Sri Lanka",
      "government lawyer",
      "legal representation",
      "AG department",
      "official website",
      "legal guidance",
      "prosecution info",
      "Sri Lanka judiciary",
      "AG portal",
      "law enforcement",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Human Rights Commission",
    url: "http://www.hrcsl.lk/",
    keywords: [
      "human rights Sri Lanka",
      "rights protection",
      "complaints",
      "legal info",
      "official portal",
      "HRC services",
      "public rights",
      "legal assistance",
      "rights violations",
      "Sri Lanka HR commission",
    ],
  },

  // health
  {
    main: "Health & Social Services 🏥💉",
    title: "Ministry of Health",
    url: "https://www.health.gov.lk/",
    keywords: [
      "Ministry of Health Sri Lanka",
      "health services",
      "hospitals info",
      "vaccination schedule",
      "govt health portal",
      "public health info",
      "health announcements",
      "official health site",
      "health programs",
      "medical services",
    ],
  },
  {
    main: "Health & Social Services 🏥💉",
    title: "National Hospital of Sri Lanka",
    url: "https://www.nhsl.health.gov.lk/",
    keywords: [
      "National Hospital Colombo",
      "hospital Sri Lanka",
      "patient info",
      "medical treatment",
      "govt hospital",
      "appointments",
      "health services",
      "public hospital info",
      "official portal",
      "medical care",
    ],
  },
  {
    main: "Health & Social Services 🏥💉",
    title: "Colombo North Teaching Hospital",
    url: "https://www.cnth.health.gov.lk/",
    keywords: [
      "Colombo North hospital",
      "teaching hospital",
      "medical services",
      "patient appointments",
      "govt hospital",
      "health info Sri Lanka",
      "medical education",
      "official hospital site",
      "public health services",
      "clinic info",
    ],
  },
  {
    main: "Health & Social Services 🏥💉",
    title: "Family Health Bureau",
    url: "https://fhb.health.gov.lk/",
    keywords: [
      "Family Health Sri Lanka",
      "maternal care",
      "child vaccination",
      "public health info",
      "health programs",
      "govt health services",
      "family planning",
      "health education",
      "official portal",
      "immunization schedule",
    ],
  },
  {
    main: "Health & Social Services 🏥💉",
    title: "Medical Research Institute",
    url: "https://www.mri.gov.lk",
    keywords: [
      "Medical Research Sri Lanka",
      "lab tests",
      "govt medical research",
      "research institutes",
      "public health studies",
      "official portal",
      "medical diagnostics",
      "health research",
      "govt health info",
      "laboratory services",
    ],
  },
  {
    main: "Health & Social Services 🏥💉",
    title: "National Blood Transfusion Service",
    url: "https://nbts.health.gov.lk/",
    keywords: [
      "blood donation Sri Lanka",
      "NBTS info",
      "blood bank",
      "govt health service",
      "official portal",
      "transfusion service",
      "public health",
      "donate blood",
      "hospital blood services",
      "health portal",
    ],
  },
  {
    main: "Health & Social Services 🏥💉",
    title: "Public Welfare Department",
    url: "",
    keywords: [
      "social welfare Sri Lanka",
      "govt assistance",
      "public aid services",
      "welfare programs",
      "official portal",
      "family support",
      "community services",
      "poverty assistance",
      "public services",
      "social help",
    ],
  },
  {
    main: "Health & Social Services 🏥💉",
    title: "Immunization Program",
    url: "https://www.epid.gov.lk/",
    keywords: [
      "vaccination Sri Lanka",
      "immunization schedule",
      "govt health program",
      "child vaccines",
      "public health",
      "official portal",
      "vaccine info",
      "health updates",
      "Sri Lanka immunization",
      "healthcare services",
    ],
  },

  // education
  {
    main: "Education & Research 🎓📚🔬",
    title: "Ministry of Education",
    url: "https://www.moe.gov.lk/",
    keywords: [
      "Ministry of Education Sri Lanka",
      "schools info",
      "curriculum",
      "education programs",
      "govt education portal",
      "official education site",
      "schools contact",
      "academic updates",
      "public education",
      "education services",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Department of Examinations",
    url: "https://www.doenets.lk/",
    keywords: [
      "Sri Lanka exams",
      "public exam results",
      "O/L results",
      "A/L results",
      "govt examination portal",
      "exam schedules",
      "official site",
      "student info",
      "exam registration",
      "examination services",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "University Grants Commission (UGC)",
    url: "https://www.ugc.ac.lk/",
    keywords: [
      "Sri Lanka universities",
      "higher education",
      "university admissions",
      "scholarships Sri Lanka",
      "official UGC portal",
      "govt universities",
      "academic programs",
      "university info",
      "research funding",
      "higher education services",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Institute of Education",
    url: "https://www.nie.ac.lk/",
    keywords: [
      "teacher training Sri Lanka",
      "curriculum development",
      "education research",
      "NIE portal",
      "official education institute",
      "academic programs",
      "teacher resources",
      "govt education services",
      "official site",
      "education research",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Vocational Training Authority (VTA)",
    url: "https://www.vta.gov.lk",
    keywords: [
      "vocational training Sri Lanka",
      "skills development",
      "technical education",
      "VTA courses",
      "govt training portal",
      "professional development",
      "official site",
      "skill certification",
      "vocational courses",
      "technical skills",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Library & Documentation Services",
    url: "https://www.natlib.lk",
    keywords: [
      "national library Sri Lanka",
      "research resources",
      "academic library",
      "govt library portal",
      "official library site",
      "documentation services",
      "public library",
      "research info",
      "scholarly resources",
      "library access",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Scholarships Division",
    url: "https://mcl.moe.gov.lk/",
    keywords: [
      "scholarships Sri Lanka",
      "govt scholarships",
      "student aid",
      "official portal",
      "education funding",
      "university scholarships",
      "academic grants",
      "financial aid",
      "scholarship programs",
      "official education site",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Postgraduate Institute of Medicine (PGIM)",
    url: "https://pgim.cmb.ac.lk/",
    keywords: [
      "PGIM Sri Lanka",
      "medical postgraduate courses",
      "govt medical education",
      "official portal",
      "medical training",
      "academic programs",
      "healthcare education",
      "professional development",
      "Sri Lanka medicine",
      "postgraduate studies",
    ],
  },

  // transport
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Department of Motor Traffic",
    url: "https://dmt.gov.lk/",
    keywords: [
      "driving license Sri Lanka",
      "vehicle registration",
      "motor traffic portal",
      "traffic fines",
      "license renewal",
      "vehicle info",
      "official DMT site",
      "road regulations",
      "Sri Lanka DMV",
      "driving test info",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Sri Lanka Transport Board (SLTB)",
    url: "https://www.sltb.lk/",
    keywords: [
      "bus schedules Sri Lanka",
      "SLTB info",
      "public transport",
      "bus tickets online",
      "govt transport services",
      "bus routes",
      "official SLTB portal",
      "travel info",
      "Sri Lanka buses",
      "bus services",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Civil Aviation Authority (CAA)",
    url: "https://www.caa.lk",
    keywords: [
      "aviation Sri Lanka",
      "flight schedules",
      "airport info",
      "airline licensing",
      "air travel info",
      "official CAA portal",
      "aviation services",
      "airport regulations",
      "Sri Lanka airlines",
      "air transport info",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Sri Lanka Railways",
    url: "https://www.railway.gov.lk/",
    keywords: [
      "train schedules Sri Lanka",
      "railway tickets",
      "public transport trains",
      "official railway portal",
      "train booking online",
      "railway updates",
      "Sri Lanka rail services",
      "train routes",
      "passenger info",
      "transport services",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "National Transport Commission",
    url: "https://www.ntc.gov.lk",
    keywords: [
      "transport regulations Sri Lanka",
      "licensing authority",
      "road safety info",
      "public transport standards",
      "NTC portal",
      "vehicle regulations",
      "official site",
      "traffic rules",
      "transport management",
      "govt transport services",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Traffic Police",
    url: "https://www.police.lk/",
    keywords: [
      "traffic fines Sri Lanka",
      "traffic rules",
      "driving violations",
      "road safety",
      "police traffic info",
      "official portal",
      "Sri Lanka traffic police",
      "ticket payment",
      "road regulations",
      "traffic updates",
    ],
  },

  // finnance
  {
    main: "Finance & Economy 💰🏦📈",
    title: "Central Bank of Sri Lanka",
    url: "https://www.cbsl.gov.lk/",
    keywords: [
      "Central Bank Sri Lanka",
      "monetary policy",
      "bank info",
      "interest rates",
      "govt financial updates",
      "official portal",
      "economic reports",
      "banking regulation",
      "CB portal",
      "financial services",
    ],
  },
  {
    main: "Finance & Economy 💰🏦📈",
    title: "Department of Inland Revenue",
    url: "http://www.ird.gov.lk/",
    keywords: [
      "tax Sri Lanka",
      "income tax",
      "VAT info",
      "govt tax portal",
      "tax payment online",
      "official IRD site",
      "tax registration",
      "business tax",
      "tax forms",
      "revenue department",
    ],
  },
  {
    main: "Finance & Economy 💰🏦📈",
    title: "Banks (Commercial & National)",
    url: "https://www.cbsl.gov.lk/en/banks-financial-institutions",
    keywords: [
      "banks Sri Lanka",
      "bank branches",
      "bank info",
      "govt bank portal",
      "financial services",
      "savings accounts",
      "bank contact",
      "loans info",
      "bank registration",
      "banking services",
    ],
  },
  {
    main: "Finance & Economy 💰🏦📈",
    title: "Registrar of Companies",
    url: "https://www.drc.gov.lk",
    keywords: [
      "company registration Sri Lanka",
      "business registration",
      "official portal",
      "start a company",
      "business licensing",
      "govt company info",
      "corporate services",
      "company forms",
      "company info online",
      "register business",
    ],
  },
  {
    main: "Finance & Economy 💰🏦📈",
    title: "Securities & Exchange Commission (SEC)",
    url: "https://www.sec.gov.lk/",
    keywords: [
      "SEC Sri Lanka",
      "stock market info",
      "share trading",
      "securities regulation",
      "official portal",
      "investor info",
      "capital market",
      "govt finance",
      "financial regulation",
      "market updates",
    ],
  },
  {
    main: "Finance & Economy 💰🏦📈",
    title: "Treasury Department",
    url: "http://www.treasury.gov.lk/",
    keywords: [
      "govt treasury Sri Lanka",
      "financial management",
      "budget info",
      "official portal",
      "public finance",
      "govt accounts",
      "fiscal policy",
      "economic reports",
      "treasury updates",
      "official finance site",
    ],
  },
  {
    main: "Finance & Economy 💰🏦📈",
    title: "Board of Investment (BOI)",
    url: "https://www.investsrilanka.com",
    keywords: [
      "investment Sri Lanka",
      "BOI portal",
      "business incentives",
      "foreign investment",
      "govt investment services",
      "investment approvals",
      "official BOI site",
      "economic development",
      "investor info",
      "corporate services",
    ],
  },
  {
    main: "Finance & Economy 💰🏦📈",
    title: "Customs Department",
    url: "http://www.customs.gov.lk/",
    keywords: [
      "customs Sri Lanka",
      "import export info",
      "duty payment",
      "official portal",
      "trade regulations",
      "shipping info",
      "govt customs site",
      "customs services",
      "import rules",
      "export rules",
    ],
  },

  // tourism
  {
    main: "Tourism, Culture & Environment 🌿🏛️🏖️",
    title: "Sri Lanka Tourism Development Authority (SLTDA)",
    url: "https://www.sltda.gov.lk/",
    keywords: [
      "Sri Lanka tourism",
      "tourist info",
      "travel guide Sri Lanka",
      "national parks",
      "heritage sites",
      "cultural centers",
      "sightseeing",
      "official tourism portal",
      "tourist attractions",
      "travel services",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛️🏖️",
    title: "Department of National Zoological Gardens",
    url: "http://www.zoo.gov.lk/",
    keywords: [
      "Sri Lanka zoo",
      "national zoo",
      "zoo info",
      "zoo opening hours",
      "animal exhibits",
      "wildlife park",
      "official zoo portal",
      "visit zoo Sri Lanka",
      "zoo tickets",
      "conservation info",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛️🏖️",
    title: "Department of Archaeology",
    url: "http://www.archaeology.gov.lk/",
    keywords: [
      "archaeology Sri Lanka",
      "heritage sites",
      "ancient monuments",
      "official portal",
      "cultural sites",
      "archaeological projects",
      "conservation info",
      "govt archaeology",
      "historic places",
      "tourism sites",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛️🏖️",
    title: "National Museums of Sri Lanka",
    url: "http://www.museum.gov.lk/",
    keywords: [
      "national museums Sri Lanka",
      "museum info",
      "cultural centers",
      "exhibits info",
      "official museum portal",
      "museum tickets",
      "historic collections",
      "art exhibitions",
      "cultural heritage",
      "museum events",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛️🏖️",
    title: "Department of Forest Conservation",
    url: "https://www.forestdept.gov.lk",
    keywords: [
      "forest conservation Sri Lanka",
      "national parks",
      "wildlife protection",
      "govt forest portal",
      "eco tourism",
      "environmental conservation",
      "forest regulations",
      "protected areas",
      "forestry services",
      "nature conservation",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛️🏖️",
    title: "Central Cultural Fund",
    url: "http://www.ccf.gov.lk/",
    keywords: [
      "cultural heritage Sri Lanka",
      "arts promotion",
      "traditional culture",
      "official portal",
      "cultural events",
      "heritage sites",
      "govt cultural fund",
      "museum support",
      "cultural programs",
      "historic preservation",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛️🏖️",
    title: "National Environment Agency",
    url: "https://www.cea.lk",
    keywords: [
      "environment Sri Lanka",
      "pollution control",
      "govt environment portal",
      "environmental services",
      "eco protection",
      "sustainable development",
      "official site",
      "environmental laws",
      "public awareness",
      "conservation programs",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛️🏖️",
    title: "Department of Wildlife Conservation",
    url: "http://www.dwc.gov.lk/",
    keywords: [
      "wildlife Sri Lanka",
      "national parks",
      "safari info",
      "animal conservation",
      "govt wildlife portal",
      "protected species",
      "eco tourism",
      "official site",
      "forest reserves",
      "wildlife regulations",
    ],
  },

  // Speial
  {
    main: "Specialized Divisions 🌾🌦️📊",
    title: "Department of Meteorology",
    url: "http://www.meteo.gov.lk/",
    keywords: [
      "Sri Lanka weather",
      "meteorology department",
      "weather forecast",
      "rainfall info",
      "cyclone updates",
      "official weather portal",
      "climate info",
      "weather alerts",
      "govt weather services",
      "meteorology Sri Lanka",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦️📊",
    title: "Department of Agriculture",
    url: "http://www.doa.gov.lk/",
    keywords: [
      "agriculture Sri Lanka",
      "farming info",
      "crop management",
      "govt agriculture portal",
      "agriculture extension services",
      "fertilizer info",
      "agri research",
      "farm guidance",
      "official agriculture site",
      "agronomy services",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦️📊",
    title: "Tea Research Institute of Sri Lanka",
    url: "http://www.tri.lk/",
    keywords: [
      "tea research Sri Lanka",
      "tea cultivation",
      "tea production",
      "agriculture research",
      "TRI portal",
      "official research site",
      "tea studies",
      "tea farming guidance",
      "tea industry info",
      "scientific research tea",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦️📊",
    title: "Coconut Research Institute",
    url: "http://www.cri.gov.lk/",
    keywords: [
      "coconut research Sri Lanka",
      "coconut farming",
      "agriculture research",
      "govt research institute",
      "official portal",
      "coconut industry info",
      "scientific studies",
      "crop improvement",
      "research publications",
      "farming guidance",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦️📊",
    title: "Rubber Research Institute of Sri Lanka",
    url: "http://www.rri.lk/",
    keywords: [
      "rubber research Sri Lanka",
      "rubber cultivation",
      "agriculture R&D",
      "official portal",
      "research institute",
      "crop guidance",
      "farm management",
      "scientific research",
      "rubber industry",
      "govt agriculture services",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦️📊",
    title: "National Science Foundation (NSF)",
    url: "http://www.nsf.ac.lk/",
    keywords: [
      "science research Sri Lanka",
      "innovation grants",
      "NSF portal",
      "research funding",
      "scientific projects",
      "official portal",
      "research support",
      "academic research",
      "government science funding",
      "R&D projects",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦️📊",
    title: "Sri Lanka Standards Institution (SLSI)",
    url: "http://www.slsi.lk/",
    keywords: [
      "SLSI standards",
      "product certification",
      "quality control",
      "official SLSI portal",
      "Sri Lanka standards",
      "testing services",
      "industrial standards",
      "official certification",
      "regulatory board",
      "govt quality assurance",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦️📊",
    title: "National Aquatic Resources Research & Development Agency (NARA)",
    url: "http://www.nara.ac.lk/",
    keywords: [
      "fisheries research Sri Lanka",
      "aquatic resources",
      "marine studies",
      "govt research portal",
      "NARA",
      "official research institute",
      "coastal management",
      "aquaculture guidance",
      "seafood industry info",
      "scientific research",
    ],
  },
];
// First Version data store end

// Search Link
function searchLink() {
  const inputValue = document
    .getElementById("search-field")
    .value.toLowerCase();

  if (!inputValue) {
    document.getElementById("result-card").innerHTML =
      "Please enter a service your want.";
    return;
  }

  const results = searchCategories(inputValue);
  displayResults(results);

  // document.getElementById("result-card").value = "";

  // category search function
  function searchCategories(searchText) {
    return services.filter(
      (service) =>
        service.title.includes(searchText) ||
        service.keywords.some((keyword) =>
          keyword.toLowerCase().includes(searchText),
        ),
    );
  }

  // display result function
  function displayResults(results) {
    const resultDiv = document.getElementById("result-card");
    resultDiv.innerHTML = "";
    resultDiv.style.display = "block";

    if (results.length === 0) {
      resultDiv.innerHTML = `
        <p>
        <i class='fa-solid fa-circle-exclamation fa-fade'></i> 
        "No results found. Please check your spelling or try different keywords.
        </p>
      `;
      return;
    }

    results.forEach((service) => {
      resultDiv.innerHTML = `
      <div class='disCard'>
        <h2>${service.title}</h2>
        <a href="${service.url}" target="_blank">              
        <span> Go to ${service.title}<i class="fa-solid fa-chevron-right"></i></span>
        </a>
      </div>
      `;
    });
  }
}
