// 1. Ministries & Departments 🏛
export const ministriesAndDepartments = [
  {
    main: "Ministries & Departments 🏛",
    title: "Presidential Secretariat",
    url: "https://presidentsoffice.gov.lk",
    keywords: [
      "president",
      "secretariat",
      "sri lanka",
      "administration",
      "executive",
      "governance",
    ],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Prime Minister's Office",
    url: "https://pmoffice.gov.lk",
    keywords: [
      "prime minister",
      "pm office",
      "cabinet",
      "administration",
      "pmo",
    ],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Office of the Cabinet of Ministers",
    url: "https://www.cabinetoffice.gov.lk/",
    keywords: ["cabinet", "ministers", "decisions", "policy", "cabinet office"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Ministry of Defence",
    url: "https://defence.lk",
    keywords: ["defence", "military", "national security", "army", "mod"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Ministry of Finance",
    url: "https://www.treasury.gov.lk/",
    keywords: ["finance", "treasury", "economy", "budget", "tax", "fiscal"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Ministry of Digital Economy",
    url: "https://www.gov.lk/",
    keywords: ["digital", "technology", "ict", "it", "innovation"],
  },
  // {
  //   main: "Ministries & Departments 🏛",
  //   title: "Ministry of Education",
  //   url: "https://moe.gov.lk",
  //   keywords: ["education", "schools", "higher education", "training"],
  // },
  {
    main: "Ministries & Departments 🏛",
    title: "Ministry of Foreign Affairs",
    url: "https://mfa.gov.lk",
    keywords: ["foreign", "tourism", "employment", "consular", "visa"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Ministry of Agriculture",
    url: "https://agrimin.gov.lk",
    keywords: ["agriculture", "land", "irrigation", "farming", "food"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Ministry of Transport",
    url: "https://transport.gov.lk",
    keywords: ["transport", "highways", "urban development", "roads"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Ministry of Health",
    url: "https://health.gov.lk",
    keywords: ["health", "media", "hospitals", "news", "medicine"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Ministry of Public Admin",
    url: "https://pubad.gov.lk/",
    keywords: ["public admin", "provincial", "local govt", "civil service"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Dept of Govt Information",
    url: "https://www.dgi.gov.lk/",
    keywords: ["news", "information", "media", "press", "dgi"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Dept of Census and Statistics",
    url: "http://statistics.gov.lk",
    keywords: ["census", "statistics", "data", "population", "survey"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Department of Pensions",
    url: "https://pensions.gov.lk",
    keywords: ["pensions", "retired", "pensioners", "benefits"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Dept of External Resources",
    url: "https://erd.gov.lk",
    keywords: ["external resources", "foreign aid", "loans", "funding"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Dept of National Budget",
    url: "https://nbd.gov.lk",
    keywords: ["budget", "finance", "treasury", "expenditure"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Dept of Public Finance",
    url: "https://publicfinance.gov.lk",
    keywords: ["public finance", "treasury", "spending", "regulations"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Dept of Import & Export Control",
    url: "http://imexport.gov.lk",
    keywords: ["import", "export", "license", "trade", "customs"],
  },
  {
    main: "Ministries & Departments 🏛",
    title: "Dept of Government Printing",
    url: "https://documents.gov.lk",
    keywords: ["gazette", "printing", "govt printer", "documents"],
  },
];

// 2. Regional & Provincial Offices 🗺
export const regionalOffices = [
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Western Provincial Council",
    url: "https://wpc.gov.lk",
    keywords: [
      "western province",
      "colombo",
      "gampaha",
      "kalutara",
      "provincial council",
      "wpc",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Central Provincial Council",
    url: "https://cp.gov.lk",
    keywords: [
      "central province",
      "kandy",
      "matale",
      "nuwara eliya",
      "provincial council",
      "cp",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Southern Provincial Council",
    url: "http://sp.gov.lk",
    keywords: [
      "southern province",
      "galle",
      "matara",
      "hambantota",
      "provincial council",
      "sp",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "North Western Provincial Council",
    url: "https://nwp.gov.lk",
    keywords: ["north western", "kurunegala", "puttalam", "wayamba", "nwp"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "North Central Provincial Council",
    url: "https://ncp.gov.lk",
    keywords: [
      "north central",
      "anuradhapura",
      "polonnaruwa",
      "provincial council",
      "ncp",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Uva Provincial Council",
    url: "https://up.gov.lk",
    keywords: ["uva", "badulla", "monaragala", "provincial council", "up"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Sabaragamuwa Provincial Council",
    url: "https://sgp.gov.lk",
    keywords: [
      "sabaragamuwa",
      "ratnapura",
      "kegalle",
      "provincial council",
      "sgp",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Northern Provincial Council",
    url: "https://np.gov.lk",
    keywords: [
      "northern province",
      "jaffna",
      "vavuniya",
      "mannar",
      "mullaitivu",
      "kilinochchi",
      "np",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Eastern Provincial Council",
    url: "https://ep.gov.lk",
    keywords: ["eastern province", "trincomalee", "batticaloa", "ampara", "ep"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Colombo District Secretariat",
    url: "http://dist.gov.lk",
    keywords: [
      "colombo district",
      "kacheri",
      "district office",
      "government services",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Gampaha District Secretariat",
    url: "http://dist.gov.lk",
    keywords: [
      "gampaha district",
      "kacheri",
      "district secretariat",
      "services",
    ],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Kandy District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["kandy district", "kacheri", "central province", "mahanuwara"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Galle District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["galle district", "kacheri", "southern", "district office"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Kurunegala District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["kurunegala district", "kacheri", "north western", "services"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Kalutara District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["kalutara district", "kacheri", "western province", "services"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Anuradhapura District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["anuradhapura", "kacheri", "north central", "district office"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Ratnapura District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["ratnapura", "kacheri", "sabaragamuwa", "district services"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Badulla District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["badulla", "kacheri", "uva province", "district office"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Matara District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["matara", "kacheri", "southern", "district services"],
  },
  {
    main: "Regional & Provincial Offices 🗺",
    title: "Jaffna District Secretariat",
    url: "http://dist.gov.lk",
    keywords: ["jaffna", "kacheri", "northern province", "district office"],
  },
];

// 3. Public Services & Utilities ⚡️🚰📮
export const publicServices = [
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Ceylon Electricity Board (CEB)",
    url: "https://ceb.lk",
    keywords: [
      "ceb",
      "electricity bill",
      "power outage",
      "bill calculator",
      "ceb care",
      "light bill",
    ],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Lanka Electricity Company (LECO)",
    url: "https://leco.lk",
    keywords: ["leco", "electricity bill", "payment", "power", "utility"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "National Water Supply & Drainage Board",
    url: "https://waterboard.lk",
    keywords: [
      "water bill",
      "nwsdb",
      "water board",
      "water supply",
      "new connection",
    ],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Sri Lanka Post",
    url: "https://slpost.gov.lk",
    keywords: [
      "postal tracking",
      "sl post",
      "courier",
      "stamps",
      "post office",
      "parcel",
    ],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Dept. for Registration of Persons (DRP)",
    url: "https://drp.gov.lk",
    keywords: ["nic", "identity card", "id card", "drp", "registration"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Dept. of Immigration & Emigration",
    url: "https://immigration.gov.lk",
    keywords: ["passport", "visa", "immigration", "eta", "foreign travel"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Registrar General's Department",
    url: "https://rgd.gov.lk",
    keywords: [
      "birth certificate",
      "marriage",
      "death certificate",
      "rgd",
      "ebmd",
      "legal documents",
    ],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Telecommunications Regulatory Commission",
    url: "https://trc.gov.lk",
    keywords: ["trc", "telecom", "internet", "spectrum", "mobile regulation"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Sri Lanka Telecom (SLT-Mobitel)",
    url: "https://sltmobitel.lk",
    keywords: ["slt", "broadband", "peo tv", "landline", "internet bill"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Dialog Axiata",
    url: "https://dialog.lk",
    keywords: ["dialog", "mobile", "broadband", "tv", "recharge"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Mobitel (Private) Limited",
    url: "https://mobitel.lk",
    keywords: ["mobitel", "mobile", "recharge", "broadband", "eselfcare"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Hutchison Telecommunications",
    url: "https://hutch.lk",
    keywords: ["hutch", "mobile", "internet", "recharge"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Airtel Sri Lanka",
    url: "https://airtel.lk",
    keywords: ["airtel", "mobile", "internet", "recharge"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Consumer Affairs Authority (CAA)",
    url: "https://caa.gov.lk",
    keywords: ["caa", "consumer protection", "complaints", "prices", "trade"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "National Fuel Pass",
    url: "https://fuelpass.gov.lk",
    keywords: ["fuel pass", "qr code", "petrol", "diesel", "fuel quota"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Lanka QR",
    url: "https://lankaqr.com",
    keywords: ["lanka qr", "digital payment", "central bank", "fintech"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Sustainable Energy Authority",
    url: "https://energy.gov.lk",
    keywords: ["solar", "renewable energy", "energy saving", "wind power"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Department of National Housing",
    url: "http://nhda.lk",
    keywords: ["housing", "apartments", "nhda", "loans", "construction"],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Sri Lanka Standards Institution (SLSI)",
    url: "http://slsi.lk",
    keywords: [
      "slsi",
      "standards",
      "quality",
      "certification",
      "product quality",
    ],
  },
  {
    main: "Public Services & Utilities ⚡️🚰📮",
    title: "Public Utilities Commission (PUCSL)",
    url: "https://pucsl.gov.lk",
    keywords: [
      "pucsl",
      "electricity regulation",
      "complaints",
      "energy policy",
    ],
  },
];

// 4. Law & Justice ⚖️👮
export const lawAndJustice = [
  {
    main: "Law & Justice ⚖️👮",
    title: "Sri Lanka Police (Official)",
    url: "https://police.lk",
    keywords: [
      "police station",
      "emergency",
      "complaint",
      "safety",
      "119",
      "police contact",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Police Clearance Certificate (e-Service)",
    url: "https://police.lkindex.php/item/512",
    keywords: [
      "police clearance",
      "certificate",
      "character certificate",
      "online application",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Ministry of Justice",
    url: "https://moj.gov.lk",
    keywords: [
      "justice ministry",
      "law",
      "legal system",
      "reforms",
      "government lawyer",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Supreme Court of Sri Lanka",
    url: "https://supremecourt.lk",
    keywords: [
      "supreme court",
      "judiciary",
      "legal rulings",
      "case info",
      "chief justice",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Court of Appeal",
    url: "http://courtofappeal.lk",
    keywords: [
      "court of appeal",
      "legal updates",
      "judgments",
      "appeals",
      "cases",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Judicial Service Commission",
    url: "https://jsc.gov.lk",
    keywords: [
      "jsc",
      "judges",
      "court administration",
      "judiciary",
      "appointments",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Attorney General’s Department",
    url: "http://attorneygeneral.gov.lk",
    keywords: [
      "attorney general",
      "ag office",
      "legal advice",
      "prosecution",
      "govt lawyer",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Legal Aid Commission of Sri Lanka",
    url: "http://legalaid.gov.lk",
    keywords: [
      "legal aid",
      "free lawyer",
      "legal help",
      "assistance",
      "public lawyers",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Bar Association of Sri Lanka (BASL)",
    url: "https://basl.lk",
    keywords: [
      "basl",
      "lawyers",
      "legal profession",
      "advocates",
      "legal events",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Human Rights Commission",
    url: "http://hrcsl.lk",
    keywords: [
      "human rights",
      "hrcsl",
      "complaints",
      "rights violation",
      "justice",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Dept. of Prisons",
    url: "http://prisons.gov.lk",
    keywords: ["prisons", "rehabilitation", "inmates", "jail", "prison info"],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Dept. of Community Based Correction",
    url: "http://cbc.gov.lk",
    keywords: [
      "correction",
      "rehabilitation",
      "probation",
      "community service",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Legal Draftsman's Department",
    url: "http://legaldraftsman.gov.lk",
    keywords: ["legal drafting", "bills", "acts", "legislation", "laws"],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Debt Conciliation Board",
    url: "http://debtconciliation.gov.lk",
    keywords: ["debt", "loans", "conciliation", "settlement", "legal help"],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Bribery & Corruption Commission (CIABOC)",
    url: "https://ciaboc.gov.lk",
    keywords: ["bribery", "corruption", "complaint", "ciaboc", "investigation"],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Official Languages Commission",
    url: "https://olc.gov.lk",
    keywords: [
      "language rights",
      "sinhala",
      "tamil",
      "english",
      "official language",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Quazi Courts (Muslim Law)",
    url: "https://moj.gov.lk",
    keywords: ["quazi", "muslim law", "marriage", "divorce", "legal info"],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Conciliation Boards (Samatha Mandala)",
    url: "https://moj.gov.lk",
    keywords: [
      "samatha mandala",
      "mediation",
      "settlement",
      "disputes",
      "village court",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Government Analyst's Department",
    url: "http://gad.gov.lk",
    keywords: [
      "forensic",
      "lab test",
      "crime scene",
      "investigation",
      "analysis",
    ],
  },
  {
    main: "Law & Justice ⚖️👮",
    title: "Child Protection Authority (NCPA)",
    url: "http://childprotection.gov.lk",
    keywords: [
      "child safety",
      "abuse",
      "complaint",
      "1929",
      "child rights",
      "ncpa",
    ],
  },
];

// 5. Health & Social Services 🏥
export const healthAndSocialServices = [
  {
    main: "Health & Social Services 🏥",
    title: "Ministry of Health (Official)",
    url: "https://health.gov.lk",
    keywords: [
      "health ministry",
      "moh",
      "hospitals",
      "medicine",
      "health updates",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Swastha Health Portal",
    url: "https://swastha.gov.lk",
    keywords: [
      "swastha",
      "medical report",
      "patient info",
      "health records",
      "online health",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "1990 Suwa Seriya (Ambulance)",
    url: "https://1990.lk",
    keywords: [
      "ambulance",
      "emergency",
      "suwa seriya",
      "hospital transfer",
      "1990",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "National Hospital of Sri Lanka (NHSL)",
    url: "https://health.gov.lk",
    keywords: [
      "colombo hospital",
      "national hospital",
      "nhsl",
      "emergency care",
      "specialists",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "National Blood Transfusion Service",
    url: "http://health.gov.lk",
    keywords: [
      "blood donation",
      "blood bank",
      "donate blood",
      "nbts",
      "plasma",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Welfare Benefits Board (Aswesuma)",
    url: "https://wbb.gov.lk",
    keywords: [
      "aswesuma",
      "welfare",
      "social safety",
      "grants",
      "benefits board",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Samurdhi Development Department",
    url: "https://samurdhi.gov.lk",
    keywords: [
      "samurdhi",
      "poverty alleviation",
      "welfare",
      "social support",
      "community",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Dept. of Social Services",
    url: "https://socialservices.gov.lk",
    keywords: [
      "social services",
      "disability support",
      "elderly care",
      "welfare",
      "vocational training",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "National Council for Elders",
    url: "https://elderscouncil.gov.lk",
    keywords: [
      "elders",
      "senior citizens",
      "identity card",
      "welfare",
      "retirement",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "National Secretariat for Persons with Disabilities",
    url: "https://disability.gov.lk",
    keywords: [
      "disability",
      "special needs",
      "support",
      "grants",
      "assistive devices",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "National Dangerous Drugs Control Board",
    url: "https://nddcb.gov.lk",
    keywords: [
      "drug control",
      "rehabilitation",
      "nddcb",
      "prevention",
      "treatment",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "State Pharmaceuticals Corporation (SPC)",
    url: "https://spc.lk",
    keywords: ["spc", "osusu sala", "medicine", "pharmacy", "drugs"],
  },
  {
    main: "Health & Social Services 🏥",
    title: "National Medicines Regulatory Authority",
    url: "https://nmra.gov.lk",
    keywords: [
      "nmra",
      "drug regulation",
      "pharmacy license",
      "medical devices",
      "cosmetics",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Ayurveda Department",
    url: "http://ayurveda.gov.lk",
    keywords: [
      "ayurveda",
      "traditional medicine",
      "herbal",
      "ayurvedic hospital",
      "indigenous",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Family Health Bureau",
    url: "https://health.gov.lk",
    keywords: [
      "maternal health",
      "child care",
      "fhb",
      "vaccination",
      "reproductive health",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Health Promotion Bureau",
    url: "https://health.gov.lk",
    keywords: [
      "hpb",
      "health education",
      "awareness",
      "diseases",
      "1999 hotline",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Sri Lanka Medical Council (SLMC)",
    url: "https://slmc.gov.lk",
    keywords: [
      "slmc",
      "doctors registry",
      "medical ethics",
      "registration",
      "mbbs",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Lady Ridgeway Hospital (LRH)",
    url: "https://health.gov.lk",
    keywords: [
      "children hospital",
      "lrh",
      "paediatric",
      "baby care",
      "specialists",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "National Cancer Institute (Apeksha)",
    url: "http://health.gov.lk",
    keywords: [
      "cancer hospital",
      "apeksha",
      "maharagama",
      "oncology",
      "treatment",
    ],
  },
  {
    main: "Health & Social Services 🏥",
    title: "Epidemiology Unit",
    url: "https://epid.gov.lk",
    keywords: [
      "dengue",
      "covid info",
      "vaccination schedule",
      "disease tracking",
      "outbreaks",
    ],
  },
];

// 6. Education & Research 🎓📚🔬
export const educationAndResearch = [
  {
    main: "Education & Research 🎓📚🔬",
    title: "Department of Examinations (Doenets)",
    url: "https://doenets.lk",
    keywords: [
      "ol results",
      "al results",
      "grade 5 scholarship",
      "exams",
      "index number",
      "past papers",
      "exam calendar",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "University Grants Commission (UGC)",
    url: "https://ugc.ac.lk",
    keywords: [
      "university admission",
      "ugc",
      "higher education",
      "degree selection",
      "z-score",
      "university portal",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Ministry of Education",
    url: "https://moe.gov.lk",
    keywords: [
      "schools",
      "teacher transfer",
      "curriculum",
      "moe",
      "national schools",
      "education policy",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Vocational Training Authority (VTA)",
    url: "https://vta.gov.lk",
    keywords: [
      "nvq",
      "vocational training",
      "vta",
      "courses",
      "skills",
      "technical training",
      "job training",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Institute of Education (NIE)",
    url: "https://nie.ac.lk",
    keywords: [
      "nie",
      "text books",
      "syllabus",
      "e-thaksalawa",
      "teacher training",
      "educational research",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Tertiary & Vocational Education Commission",
    url: "https://tvec.gov.lk",
    keywords: [
      "tvec",
      "nvq certificate",
      "skills registration",
      "vocational standards",
      "training providers",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Library of Sri Lanka",
    url: "http://natlib.lk",
    keywords: [
      "library",
      "research",
      "books",
      "documentation",
      "isbn",
      "national library",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Science Foundation (NSF)",
    url: "http://nsf.ac.lk",
    keywords: [
      "science",
      "nsf",
      "research grants",
      "innovation",
      "scientific research",
      "technology",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Department of Technical Education & Training",
    url: "http://dtet.gov.lk",
    keywords: [
      "technical college",
      "dtet",
      "vocational",
      "diploma",
      "engineering courses",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Sri Lanka Institute of Advanced Technological Education",
    url: "https://sliate.ac.lk",
    keywords: [
      "sliate",
      "hnda",
      "hnd",
      "higher diploma",
      "ati",
      "advanced technology",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Apprentice & Industrial Training Authority",
    url: "http://naita.gov.lk",
    keywords: [
      "naita",
      "apprenticeship",
      "on-the-job training",
      "technical skills",
      "industry training",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Arthur C. Clarke Institute (ACCIMT)",
    url: "https://accimt.ac.lk",
    keywords: [
      "space technology",
      "electronics",
      "robotics",
      "accimt",
      "it research",
      "communications",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Industrial Technology Institute (ITI)",
    url: "https://iti.lk",
    keywords: [
      "iti",
      "food testing",
      "industrial research",
      "lab services",
      "product testing",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Sri Lanka Institute of Development Admin (SLIDA)",
    url: "https://slida.lk",
    keywords: [
      "slida",
      "public service training",
      "management",
      "administration",
      "govt training",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Youth Services Council (NYSC)",
    url: "https://nysc.lk",
    keywords: [
      "youth council",
      "nysc",
      "maharagama",
      "youth training",
      "clubs",
      "youth skills",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Science Center",
    url: "https://nsc.gov.lk",
    keywords: [
      "science museum",
      "science center",
      "education",
      "science exhibits",
      "learning",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "National Research Council (NRC)",
    url: "https://nrc.gov.lk",
    keywords: [
      "nrc",
      "investigator grants",
      "research funding",
      "science grants",
      "govt research",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Postgraduate Institute of Science (PGIS)",
    url: "https://pdn.ac.lk",
    keywords: [
      "pgis",
      "postgraduate",
      "msc",
      "phd",
      "science research",
      "peradeniya",
    ],
  },

  {
    main: "Education & Research 🎓📚🔬",
    title: "Educational Publications Department",
    url: "http://edupub.gov.lk",
    keywords: [
      "school books",
      "e-books",
      "textbook download",
      "free books",
      "govt printing",
    ],
  },
  {
    main: "Education & Research 🎓📚🔬",
    title: "Scholarships Division (Ministry of Education)",
    url: "https://moe.gov.lk",
    keywords: [
      "scholarships",
      "foreign scholarships",
      "student grants",
      "bursary",
      "education funding",
    ],
  },
];

// 7. Transport & Vehicle Management 🚗🚌
export const transportAndVehicleManagement = [
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Dept. of Motor Traffic (DMT/RMV)",
    url: "https://dmt.gov.lk",
    keywords: [
      "driving license",
      "vehicle registration",
      "rmv",
      "dmt",
      "number plate",
      "license renewal",
      "werahera",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Sri Lanka Railways (Official)",
    url: "https://railway.gov.lk",
    keywords: [
      "train schedule",
      "railway",
      "train ticket",
      "seat booking",
      "fort station",
      "train time table",
      "slr",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Sri Lanka Transport Board (SLTB)",
    url: "https://sltb.lk",
    keywords: [
      "sltb",
      "bus schedule",
      "ctb",
      "bus booking",
      "public transport",
      "bus routes",
      "london bus",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "National Transport Commission (NTC)",
    url: "https://ntc.gov.lk",
    keywords: [
      "ntc",
      "bus fare",
      "private bus",
      "bus license",
      "transport regulation",
      "complaints",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Civil Aviation Authority (CAA)",
    url: "https://caa.lk",
    keywords: [
      "aviation",
      "drone license",
      "flight safety",
      "airline",
      "airport regulation",
      "caa",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Airport & Aviation Services (AASL)",
    url: "https://airport.lk",
    keywords: [
      "airport",
      "katunayake",
      "flight status",
      "arrivals",
      "departures",
      "bia",
      "mria",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Department of Coast Guard",
    url: "http://coastguard.gov.lk",
    keywords: [
      "coast guard",
      "maritime",
      "sea safety",
      "rescue",
      "coastal security",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Sri Lanka Ports Authority (SLPA)",
    url: "https://slpa.lk",
    keywords: [
      "port",
      "harbour",
      "colombo port",
      "shipping",
      "logistics",
      "vessel",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Merchant Shipping Secretariat",
    url: "http://dgshipping.gov.lk",
    keywords: [
      "shipping",
      "seaman",
      "cdc",
      "vessel registration",
      "maritime license",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Marine Environment Protection Authority",
    url: "https://mepa.gov.lk",
    keywords: [
      "mepa",
      "marine pollution",
      "ocean protection",
      "oil spill",
      "sea environment",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "National Council for Road Safety",
    url: "https://transport.gov.lk",
    keywords: [
      "road safety",
      "accident prevention",
      "traffic rules",
      "pedestrian safety",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Road Development Authority (RDA)",
    url: "https://rda.gov.lk",
    keywords: [
      "rda",
      "highways",
      "expressway",
      "road construction",
      "bridges",
      "e01",
      "e02",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Expressway Operation & Maintenance",
    url: "http://rda.gov.lk",
    keywords: [
      "expressway toll",
      "highway entrance",
      "rda exway",
      "highway updates",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "SriLankan Airlines",
    url: "https://srilankan.com",
    keywords: [
      "srilankan",
      "flight booking",
      "airline",
      "air ticket",
      "ul flight",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Mihin Lanka (Information)",
    url: "https://transport.gov.lk",
    keywords: ["mihin lanka", "aviation", "govt airline"],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Highway Museum - Kiribathkumbura",
    url: "https://rda.gov.lk",
    keywords: ["highway museum", "rda museum", "kandy road", "historic roads"],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Vehicle Revenue License (e-Service)",
    url: "https://wp.gov.lk",
    keywords: [
      "revenue license",
      "income tax vehicle",
      "western province license",
      "online revenue",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Lanka Logistics & Technologies",
    url: "https://lltl.lk",
    keywords: [
      "logistics",
      "govt procurement",
      "technology",
      "transport systems",
    ],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Sahasara (Bus Tracking)",
    url: "https://ntc.gov.lk",
    keywords: ["sahasara", "bus tracking", "smart transport", "gps bus"],
  },
  {
    main: "Transport & Vehicle Management 🚗🚌",
    title: "Urban Development Authority (UDA)",
    url: "https://uda.gov.lk",
    keywords: [
      "uda",
      "parking",
      "urban planning",
      "city development",
      "town planning",
    ],
  },
];

// 8. Finance & Economy 💰
export const financeAndEconomy = [
  {
    main: "Finance & Economy 💰",
    title: "Inland Revenue Department (IRD)",
    url: "http://ird.gov.lk",
    keywords: [
      "tax",
      "tin number",
      "vat",
      "income tax",
      "ird",
      "tax return",
      "e-services",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Central Bank of Sri Lanka (CBSL)",
    url: "https://cbsl.gov.lk",
    keywords: [
      "central bank",
      "cbsl",
      "exchange rate",
      "dollar rate",
      "inflation",
      "monetary policy",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Employee Provident Fund (EPF)",
    url: "https://epf.lk",
    keywords: [
      "epf",
      "provident fund",
      "retirement",
      "epf balance",
      "cbsl epf",
      "30 percent",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Employees' Trust Fund Board (ETF)",
    url: "http://etfb.lk",
    keywords: [
      "etf",
      "trust fund",
      "etf claim",
      "etf balance",
      "employment benefits",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Sri Lanka Customs",
    url: "http://customs.gov.lk",
    keywords: [
      "customs",
      "import tax",
      "duty free",
      "vehicle tax",
      "shipping duty",
      "customs tariff",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Dept. of Census & Statistics",
    url: "http://statistics.gov.lk",
    keywords: [
      "statistics",
      "census",
      "data",
      "gdp",
      "population",
      "inflation rate",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Board of Investment (BOI)",
    url: "https://investsrilanka.com",
    keywords: [
      "boi",
      "investment",
      "business sri lanka",
      "foreign investment",
      "export processing",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Export Development Board (EDB)",
    url: "https://srilankabusiness.com",
    keywords: [
      "edb",
      "export",
      "sri lanka business",
      "export products",
      "trade info",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Department of Registrar of Companies",
    url: "https://drc.gov.lk",
    keywords: [
      "company registration",
      "eroc",
      "business name",
      "pvt ltd",
      "drc",
      "register company",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Colombo Stock Exchange (CSE)",
    url: "https://cse.lk",
    keywords: [
      "stock exchange",
      "cse",
      "shares",
      "stock market",
      "investing",
      "aspi",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Securities & Exchange Commission",
    url: "https://sec.gov.lk",
    keywords: [
      "sec",
      "stock regulation",
      "capital market",
      "investment safety",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Credit Information Bureau (CRIB)",
    url: "https://crib.lk",
    keywords: [
      "crib",
      "credit report",
      "bank loan",
      "credit history",
      "loan eligibility",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Bank of Ceylon (BOC)",
    url: "https://boc.lk",
    keywords: ["boc", "government bank", "savings", "loans", "online banking"],
  },
  {
    main: "Finance & Economy 💰",
    title: "People's Bank",
    url: "https://peoplesbank.lk",
    keywords: [
      "peoples bank",
      "govt bank",
      "loans",
      "savings",
      "digital banking",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "National Savings Bank (NSB)",
    url: "https://nsb.lk",
    keywords: ["nsb", "savings", "fixed deposit", "govt bank", "pension"],
  },
  {
    main: "Finance & Economy 💰",
    title: "Sri Lanka Insurance (SLIC)",
    url: "https://srilankainsurance.com",
    keywords: [
      "insurance",
      "slic",
      "life insurance",
      "vehicle insurance",
      "full insurance",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Department of National Budget",
    url: "https://nbd.gov.lk",
    keywords: [
      "budget",
      "govt spending",
      "national budget",
      "treasury",
      "expenditure",
    ],
  },
  {
    main: "Finance & Economy 💰",
    title: "Department of Treasury Operations",
    url: "https://treasury.gov.lk",
    keywords: ["treasury", "public finance", "govt funds", "finance ministry"],
  },
  {
    main: "Finance & Economy 💰",
    title: "Sri Lanka Export Credit Insurance",
    url: "https://slecic.lk",
    keywords: ["slecic", "export insurance", "trade credit", "export support"],
  },
  {
    main: "Finance & Economy 💰",
    title: "Public Enterprises Department",
    url: "https://ped.gov.lk",
    keywords: [
      "public enterprise",
      "govt business",
      "monitoring",
      "ped",
      "state owned",
    ],
  },
];

// 9. Tourism, Culture & Environment 🌿🏛🏖
export const tourismCultureAndEnvironment = [
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Sri Lanka Tourism Development Authority (SLTDA)",
    url: "https://sltda.gov.lk",
    keywords: [
      "tourism",
      "travel",
      "visit sri lanka",
      "hotels",
      "tourist info",
      "sltda",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Dept. of Wildlife Conservation (DWC)",
    url: "https://dwc.gov.lk",
    keywords: [
      "wildlife",
      "safari",
      "yala",
      "wilpattu",
      "national park",
      "animal protection",
      "dwc",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Department of Meteorology",
    url: "http://meteo.gov.lk",
    keywords: [
      "weather",
      "rain",
      "forecast",
      "climate",
      "temperature",
      "cyclone",
      "meteo",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Department of National Museums",
    url: "https://museum.gov.lk",
    keywords: [
      "museum",
      "history",
      "artifacts",
      "colombo museum",
      "culture",
      "heritage",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Department of Archaeology",
    url: "http://archaeology.gov.lk",
    keywords: [
      "archaeology",
      "ancient sites",
      "historical monuments",
      "conservation",
      "ruins",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Central Cultural Fund (CCF)",
    url: "https://ccf.gov.lk",
    keywords: [
      "cultural fund",
      "heritage",
      "sigiriya",
      "polonnaruwa",
      "temples",
      "monuments",
      "ccf",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Department of Forest Conservation",
    url: "https://forestdept.gov.lk",
    keywords: [
      "forest",
      "nature",
      "conservation",
      "sinharaja",
      "trees",
      "wildlife",
      "environment",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Central Environmental Authority (CEA)",
    url: "https://cea.lk",
    keywords: [
      "environment",
      "pollution",
      "cea",
      "epl",
      "waste management",
      "nature protection",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Department of National Zoological Gardens",
    url: "https://zoo.gov.lk",
    keywords: [
      "zoo",
      "animals",
      "dehiwala zoo",
      "pinnawala",
      "elephant orphanage",
      "ridiyagama",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "National Botanical Gardens",
    url: "https://botanicgardens.gov.lk",
    keywords: [
      "botanical gardens",
      "peradeniya",
      "flowers",
      "plants",
      "nature",
      "hakgala",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Sri Lanka Convention Bureau",
    url: "https://slcb.lk",
    keywords: [
      "events",
      "business travel",
      "conventions",
      "meetings",
      "mice tourism",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Marine Environment Protection Authority (MEPA)",
    url: "https://mepa.gov.lk",
    keywords: [
      "marine",
      "ocean",
      "sea pollution",
      "mepa",
      "coastal protection",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Sustainable Energy Authority",
    url: "https://energy.gov.lk",
    keywords: [
      "solar",
      "wind energy",
      "sustainable",
      "power saving",
      "renewable",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Geological Survey & Mines Bureau (GSMB)",
    url: "https://gsmb.gov.lk",
    keywords: [
      "mining",
      "minerals",
      "geology",
      "gsmb",
      "earthquake",
      "sand mining",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Department of National Archives",
    url: "http://archives.gov.lk",
    keywords: [
      "archives",
      "history",
      "old records",
      "documents",
      "historical library",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "National Film Corporation",
    url: "http://nfc.gov.lk",
    keywords: ["cinema", "movies", "film industry", "nfc", "theaters"],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Department of Cultural Affairs",
    url: "http://culturaldept.gov.lk",
    keywords: [
      "culture",
      "arts",
      "traditional",
      "dance",
      "festivals",
      "sinhala tamil culture",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Tower Hall Theatre Foundation",
    url: "http://towerhall.lk",
    keywords: [
      "drama",
      "theatre",
      "plays",
      "tower hall",
      "maradana",
      "performing arts",
    ],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Coast Conservation & Coastal Resource Management",
    url: "http://coastal.gov.lk",
    keywords: ["coast", "beach", "sea erosion", "maritime", "shore protection"],
  },
  {
    main: "Tourism, Culture & Environment 🌿🏛🏖",
    title: "Sri Lanka Tourism Promotion Bureau",
    url: "https://srilanka.travel",
    keywords: [
      "travel",
      "promotion",
      "visit sri lanka",
      "tourism marketing",
      "destinations",
    ],
  },
];

// 10. Specialized Divisions 🌾🌦📊
export const specializedDivisions = [
  // {
  //   main: "Specialized Divisions 🌾🌦📊",
  //   title: "Department of Meteorology",
  //   url: "http://www.meteo.gov.lk/",
  //   keywords: [
  //     "weather",
  //     "rain",
  //     "forecast",
  //     "climate",
  //     "meteo",
  //     "rainfall",
  //     "cyclone",
  //     "weather alert",
  //   ],
  // },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Department of Agriculture",
    url: "http://www.doa.gov.lk/",
    keywords: [
      "agriculture",
      "farming",
      "crop",
      "doa",
      "fertilizer",
      "agri research",
      "extension services",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Sri Lanka Standards Institution (SLSI)",
    url: "http://www.slsi.lk/",
    keywords: [
      "slsi",
      "standards",
      "quality",
      "certification",
      "iso",
      "sls mark",
      "testing",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Tea Research Institute (TRI)",
    url: "http://www.tri.lk/",
    keywords: [
      "tea research",
      "tri",
      "tea cultivation",
      "tea industry",
      "scientific research",
      "talawakelle",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Coconut Research Institute (CRI)",
    url: "http://www.cri.gov.lk/",
    keywords: [
      "coconut research",
      "cri",
      "lunuwila",
      "coconut farming",
      "pest control",
      "crop improvement",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Rubber Research Institute (RRI)",
    url: "http://www.rri.lk/",
    keywords: [
      "rubber research",
      "rri",
      "rubber cultivation",
      "latex",
      "rubber industry",
      "scientific research",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "National Science Foundation (NSF)",
    url: "http://www.nsf.ac.lk/",
    keywords: [
      "nsf",
      "science research",
      "innovation",
      "research grants",
      "scientific projects",
      "funding",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "National Aquatic Resources Agency (NARA)",
    url: "http://www.nara.ac.lk/",
    keywords: [
      "nara",
      "fisheries",
      "marine research",
      "aquatic",
      "oceanography",
      "coastal research",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Industrial Technology Institute (ITI)",
    url: "https://iti.lk",
    keywords: [
      "iti",
      "industrial research",
      "food testing",
      "lab services",
      "product development",
      "cisir",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Sustainable Energy Authority",
    url: "https://energy.gov.lk",
    keywords: [
      "renewable energy",
      "solar",
      "wind power",
      "energy saving",
      "sustainable",
      "energy policy",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Atomic Energy Regulatory Council",
    url: "http://aerc.gov.lk",
    keywords: [
      "atomic energy",
      "radiation",
      "nuclear safety",
      "aerc",
      "regulatory",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "National Engineering R&D Centre (NERD)",
    url: "http://nerdc.lk",
    keywords: [
      "nerd",
      "engineering research",
      "innovation",
      "machinery",
      "technical development",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Geological Survey & Mines Bureau (GSMB)",
    url: "https://gsmb.gov.lk",
    keywords: [
      "gsmb",
      "mining",
      "minerals",
      "earthquake",
      "geology",
      "sand mining license",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "National Building Research Organisation",
    url: "https://nbro.gov.lk",
    keywords: [
      "nbro",
      "landslide",
      "building safety",
      "soil testing",
      "disaster prevention",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Coast Conservation Department",
    url: "https://coastal.gov.lk",
    keywords: [
      "coast conservation",
      "beach protection",
      "sea erosion",
      "coastal management",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Marine Environment Protection Authority",
    url: "https://mepa.gov.lk",
    keywords: [
      "mepa",
      "marine pollution",
      "ocean protection",
      "oil spill",
      "sea environment",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Department of Export Agriculture",
    url: "http://exportagri.gov.lk",
    keywords: [
      "spices",
      "cinnamon",
      "pepper",
      "export crops",
      "minor export crops",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Rice Research & Development Institute",
    url: "http://rrdi.gov.lk",
    keywords: [
      "rice research",
      "paddy",
      "rrdi",
      "bathalagoda",
      "rice varieties",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "Gem & Jewellery Authority",
    url: "https://ngja.gov.lk",
    keywords: [
      "gem",
      "jewellery",
      "mining license",
      "gem testing",
      "blue sapphire",
      "ngja",
    ],
  },
  {
    main: "Specialized Divisions 🌾🌦📊",
    title: "National Youth Services Council",
    url: "https://nysc.lk",
    keywords: [
      "youth",
      "nysc",
      "skills",
      "vocational",
      "youth training",
      "clubs",
    ],
  },
];

// servicesData.js
export const services = [
  ...ministriesAndDepartments,
  ...regionalOffices,
  ...publicServices,
  ...lawAndJustice,
  ...healthAndSocialServices,
  ...educationAndResearch,
  ...transportAndVehicleManagement,
  ...financeAndEconomy,
  ...tourismCultureAndEnvironment,
  ...specializedDivisions,
];
